name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create simple index.html
        run: |
          mkdir -p ./public
          cat > ./public/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>ZeroDev Token Shop</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 2rem;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                      min-height: 100vh;
                  }
                  .container {
                      background: rgba(255, 255, 255, 0.1);
                      padding: 2rem;
                      border-radius: 20px;
                      backdrop-filter: blur(10px);
                      box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
                  }
                  h1 { text-align: center; margin-bottom: 2rem; }
                  .status { 
                      background: rgba(0, 255, 0, 0.2); 
                      padding: 1rem; 
                      border-radius: 10px; 
                      margin: 1rem 0;
                      border-left: 4px solid #00ff00;
                  }
                  .info {
                      background: rgba(255, 255, 255, 0.1);
                      padding: 1rem;
                      border-radius: 10px;
                      margin: 1rem 0;
                  }
                  a { color: #87ceeb; text-decoration: none; }
                  a:hover { text-decoration: underline; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🚀 ZeroDev Token Shop</h1>
                  
                  <div class="status">
                      <h3>✅ Deployment Status: SUCCESS</h3>
                      <p>GitHub Pages deployment is working correctly!</p>
                      <p><strong>Deployed at:</strong> $(date)</p>
                  </div>
                  
                  <div class="info">
                      <h3>📋 Project Information</h3>
                      <ul>
                          <li><strong>Framework:</strong> Next.js 15.3.3</li>
                          <li><strong>Blockchain:</strong> Ethereum Sepolia</li>
                          <li><strong>Wallet:</strong> Privy + ZeroDev</li>
                          <li><strong>Testing:</strong> Playwright E2E + Jest Unit</li>
                          <li><strong>Pipeline:</strong> GitHub Actions</li>
                      </ul>
                  </div>
                  
                  <div class="info">
                      <h3>🔗 Links</h3>
                      <ul>
                          <li><a href="https://github.com/govinda777/zerodev-token-shop" target="_blank">GitHub Repository</a></li>
                          <li><a href="https://github.com/govinda777/zerodev-token-shop/actions" target="_blank">CI/CD Pipeline</a></li>
                      </ul>
                  </div>
                  
                  <div class="info">
                      <h3>🚧 Development Status</h3>
                      <p>The full Next.js application is currently being optimized for production deployment. 
                      This static page confirms that the GitHub Pages deployment pipeline is working correctly.</p>
                      
                      <p><strong>Next Steps:</strong></p>
                      <ul>
                          <li>✅ GitHub Pages deployment working</li>
                          <li>🔄 Resolve WalletConnect dependency conflicts</li>
                          <li>🔄 Fix TypeScript issues in test files</li>
                          <li>🔄 Enable full Next.js static export</li>
                      </ul>
                  </div>
              </div>
          </body>
          </html>
          EOF
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
